- hosts: all
  become: yes
  tasks: 
  - name: Install apache 
    ansible.builtin.apt:
      name: tree
    register: kaizen
  - name: Debug        #more information about error
    debug: msg="{{ kaizen }}"