- hosts: all
  become: yes
  tasks:
  - name: Print OS
    debug: 
      msg: "{{ ansible_distribution }}"   #special variable = to this vm ubuntu

  - name: Install Apache
    include_tasks: "{{ ansible_distribution }}.yml"