- hosts: all
  become: yes
  tasks: 
    - name: Add the user 
      ansible.builtin.user:
        name: "{{ item }}"   #special variable "item" for loops
      loop:
        - kaizen
        - hello
        - world
